# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libcfitsio
      run: sudo apt-get install libcfitsio-dev
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: astropy
    - name: Install conda dependencies
      run: |
        conda install pip jupyter_client nbformat ipykernel matplotlib pytest
    - name: Install pip dependencies
      run: |
        python -m pip install git+https://github.com/oirlab/tmt-crds.git https://github.com/spacetelescope/jwst/archive/0.13.7.zip nbval
    - name: Setup CRDS
      run: |
        git clone --depth 1 https://github.com/oirlab/tmt-crds-cache $HOME/crds_cache && source setup_local_crds.sh
    - name: Build
      run: python setup.py build_ext -i && python setup.py install
      env:
          C_INCLUDE_PATH: /usr/include/cfitsio/
    - name: Test
      run: |
        python setup.py test
